name: xenolauncher
description: "A new Flutter project."
publish_to: 'none'   # Bu uygulama pub.dev'de yayınlanmayacak
version: 0.1.0       # Uygulama versiyonu


environment:
  sdk: ^3.5.4          # Flutter SDK versiyonu

dependencies:
  cupertino_icons: ^1.0.8    # iOS stil ikonlar için
  dotlottie_loader: ^0.0.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2    # Güvenli veri depolama için  
  go_router: ^14.6.2                  # Sayfa yönlendirme (routing) için
  lottie: ^3.1.3
  shared_preferences: ^2.3.3       # Basit veri depolama için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0           # Kod kalitesi kontrolleri için

flutter:
  uses-material-design: true       # Material Design widget'larını kullanmak için
  assets:                        # Projedeki dosya kaynakları
    - assets/images/          # Görseller için
    - assets/icons/            # İkonlar için
    - assets/languages/         # Dil dosyaları için
    - assets/motions/           # Animasyon dosyaları için
